# src/html_report.py
"""
Generates a self-contained HTML report for both analysis modes:
  - Mode 1: Dataset Analysis
  - Mode 2: Patient Assessment
"""

import math
import numpy as np
from datetime import datetime
from reference_ranges import REFERENCE_RANGES
from chart_builder import (
    build_histogram,
    build_correlation_heatmap,
    build_missing_data_chart,
    build_anomaly_bar_chart,
    build_sepsis_comparison,
    build_gender_breakdown,
    fig_to_html,
)

# ------------------------------------------------------------------------------
# HTML SHELL — the page template
# ------------------------------------------------------------------------------

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{page_title}</title>
  <meta name="description" content="Hospital patient data analysis report generated by Hospital Patient Analyzer.">
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
    :root {{
      --bg:        #0d1117;
      --surface:   #161b22;
      --surface2:  #1c2128;
      --border:    #30363d;
      --text:      #c9d1d9;
      --text-dim:  #8b949e;
      --green:     #3fb950;
      --amber:     #e3b341;
      --red:       #f85149;
      --blue:      #58a6ff;
      --purple:    #bc8cff;
      --radius:    12px;
      --font:      'Inter', system-ui, sans-serif;
    }}
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    html {{ scroll-behavior: smooth; }}
    body {{
      background: var(--bg);
      color: var(--text);
      font-family: var(--font);
      font-size: 14px;
      line-height: 1.6;
    }}
    /* -- Layout ---------------------------------- */
    .page-wrap {{ max-width: 1200px; margin: 0 auto; padding: 0 24px 80px; }}
    /* -- Top Banner ------------------------------ */
    .banner {{
      background: linear-gradient(135deg, #161b22 0%, #1c2128 50%, #0d1117 100%);
      border-bottom: 1px solid var(--border);
      padding: 40px 24px 32px;
      text-align: center;
      position: relative;
      overflow: hidden;
    }}
    .banner::before {{
      content: '';
      position: absolute;
      inset: 0;
      background: radial-gradient(ellipse at 50% -20%, rgba(88,166,255,0.08) 0%, transparent 70%);
    }}
    .banner-icon {{ font-size: 48px; display: block; margin-bottom: 12px; }}
    .banner h1 {{ font-size: 28px; font-weight: 700; color: #fff; letter-spacing: -0.5px; }}
    .banner .subtitle {{ color: var(--text-dim); margin-top: 6px; font-size: 13px; }}
    .banner .badge {{
      display: inline-block;
      margin-top: 14px;
      padding: 4px 14px;
      border-radius: 20px;
      font-size: 11px;
      font-weight: 600;
      letter-spacing: 0.5px;
      text-transform: uppercase;
    }}
    .badge-dataset {{ background: rgba(88,166,255,0.15); color: var(--blue); border: 1px solid rgba(88,166,255,0.3); }}
    .badge-patient {{ background: rgba(63,185,80,0.15); color: var(--green); border: 1px solid rgba(63,185,80,0.3); }}
    /* -- Nav tabs -------------------------------- */
    .tab-nav {{
      display: flex;
      gap: 4px;
      padding: 20px 0 0;
      border-bottom: 1px solid var(--border);
      overflow-x: auto;
    }}
    .tab-btn {{
      padding: 10px 20px;
      background: none;
      border: none;
      border-bottom: 2px solid transparent;
      color: var(--text-dim);
      font-family: var(--font);
      font-size: 13px;
      font-weight: 500;
      cursor: pointer;
      white-space: nowrap;
      transition: color 0.2s, border-color 0.2s;
    }}
    .tab-btn:hover {{ color: var(--text); }}
    .tab-btn.active {{ color: var(--blue); border-bottom-color: var(--blue); }}
    .tab-panel {{ display: none; padding-top: 28px; }}
    .tab-panel.active {{ display: block; }}
    /* -- Stat Cards ------------------------------ */
    .stat-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 14px; margin: 24px 0; }}
    .stat-card {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 20px 16px;
      text-align: center;
      transition: border-color 0.2s, transform 0.15s;
    }}
    .stat-card:hover {{ border-color: var(--blue); transform: translateY(-2px); }}
    .stat-card .value {{ font-size: 28px; font-weight: 700; color: var(--blue); }}
    .stat-card .label {{ font-size: 12px; color: var(--text-dim); margin-top: 4px; text-transform: uppercase; letter-spacing: 0.5px; }}
    .stat-card .icon {{ font-size: 22px; margin-bottom: 8px; }}
    /* -- Section headings ------------------------ */
    .section-title {{
      font-size: 17px;
      font-weight: 600;
      color: #fff;
      margin: 32px 0 16px;
      padding-bottom: 10px;
      border-bottom: 1px solid var(--border);
      display: flex;
      align-items: center;
      gap: 8px;
    }}
    .section-title .icon {{ font-size: 20px; }}
    /* -- Data Table ------------------------------ */
    .data-table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
    .data-table th {{
      background: var(--surface2);
      color: var(--text-dim);
      font-weight: 600;
      padding: 10px 14px;
      text-align: left;
      border-bottom: 1px solid var(--border);
      text-transform: uppercase;
      font-size: 11px;
      letter-spacing: 0.5px;
    }}
    .data-table td {{
      padding: 10px 14px;
      border-bottom: 1px solid var(--border);
      vertical-align: middle;
    }}
    .data-table tr:hover td {{ background: var(--surface2); }}
    .data-table .num {{ font-family: 'Courier New', monospace; font-size: 13px; }}
    /* -- Chart wrapper --------------------------- */
    .chart-wrap {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 16px;
      margin-bottom: 20px;
      overflow: hidden;
    }}
    .chart-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(460px, 1fr)); gap: 16px; }}
    /* -- Traffic lights (Patient mode) ------------ */
    .vital-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 14px; margin: 20px 0; }}
    .vital-card {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 18px 16px;
      position: relative;
      overflow: hidden;
      transition: transform 0.15s;
    }}
    .vital-card:hover {{ transform: translateY(-2px); }}
    .vital-card::before {{
      content: '';
      position: absolute;
      top: 0; left: 0;
      width: 4px; height: 100%;
      background: var(--status-color, var(--border));
    }}
    .vital-card .vc-head {{ display: flex; justify-content: space-between; align-items: flex-start; }}
    .vital-card .vc-name {{ font-weight: 600; font-size: 14px; color: #fff; }}
    .vital-card .vc-status {{
      font-size: 11px;
      font-weight: 700;
      padding: 3px 10px;
      border-radius: 20px;
      background: rgba(0,0,0,0.3);
      color: var(--status-color, var(--text));
      border: 1px solid var(--status-color, var(--border));
    }}
    .vital-card .vc-value {{ font-size: 26px; font-weight: 700; color: var(--status-color, var(--text)); margin: 8px 0 4px; }}
    .vital-card .vc-unit {{ font-size: 12px; color: var(--text-dim); }}
    .vital-card .vc-range {{ font-size: 12px; color: var(--text-dim); margin-top: 4px; }}
    .vital-card .vc-desc {{ font-size: 12px; color: var(--text-dim); margin-top: 8px; padding-top: 8px; border-top: 1px solid var(--border); line-height: 1.5; }}
    .vital-card .vc-msg {{ font-size: 12px; margin-top: 6px; padding: 8px; border-radius: 6px; background: rgba(0,0,0,0.2); line-height: 1.5; color: var(--text); }}
    /* -- Plain-English box ----------------------- */
    .plain-box {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-left: 4px solid var(--blue);
      border-radius: var(--radius);
      padding: 18px 20px;
      margin-bottom: 16px;
    }}
    .plain-box h3 {{ font-size: 14px; font-weight: 600; color: #fff; margin-bottom: 8px; }}
    .plain-box p  {{ font-size: 13px; color: var(--text); line-height: 1.65; }}
    /* -- Alert box ------------------------------- */
    .alert {{
      border-radius: var(--radius);
      padding: 14px 18px;
      margin: 16px 0;
      font-size: 13px;
      line-height: 1.6;
      display: flex;
      gap: 10px;
      align-items: flex-start;
    }}
    .alert-info   {{ background: rgba(88,166,255,0.1);  border: 1px solid rgba(88,166,255,0.3);  color: #8ec5f5; }}
    .alert-warn   {{ background: rgba(227,179,65,0.1);  border: 1px solid rgba(227,179,65,0.3);  color: var(--amber); }}
    .alert-danger {{ background: rgba(248,81,73,0.1);   border: 1px solid rgba(248,81,73,0.3);   color: #f8a5a0; }}
    /* -- Collapsible ----------------------------- */
    .collapsible {{ margin-bottom: 12px; }}
    .collapsible summary {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 12px 16px;
      cursor: pointer;
      font-weight: 500;
      color: var(--text);
      list-style: none;
      display: flex;
      align-items: center;
      gap: 8px;
      transition: background 0.15s;
    }}
    .collapsible summary:hover {{ background: var(--surface2); }}
    .collapsible summary::after {{ content: ' ▾'; margin-left: auto; color: var(--text-dim); }}
    .collapsible[open] summary::after {{ content: ' ▴'; }}
    .collapsible .collapsible-body {{ padding: 16px 0; }}
    /* -- Footer ---------------------------------- */
    footer {{
      margin-top: 60px;
      padding: 24px;
      border-top: 1px solid var(--border);
      text-align: center;
      font-size: 12px;
      color: var(--text-dim);
      line-height: 1.7;
    }}
    footer strong {{ color: var(--text); }}
    /* -- Progress bar ---------------------------- */
    .progress-wrap {{ margin: 6px 0; }}
    .progress-bar {{
      height: 6px;
      border-radius: 3px;
      background: var(--border);
      overflow: hidden;
    }}
    .progress-fill {{
      height: 100%;
      border-radius: 3px;
      transition: width 0.4s ease;
    }}
    /* -- Scrollable table wrapper ---------------- */
    .table-wrap {{ overflow-x: auto; border-radius: var(--radius); border: 1px solid var(--border); }}
    /* -- Responsive ------------------------------ */
    @media (max-width: 640px) {{
      .banner h1 {{ font-size: 20px; }}
      .stat-card .value {{ font-size: 22px; }}
      .chart-grid {{ grid-template-columns: 1fr; }}
    }}
  </style>
</head>
<body>

{banner_html}

<div class="page-wrap">
  <nav class="tab-nav" id="tab-nav">
{tab_buttons}
  </nav>

{tab_panels}

  <footer>
    <strong>Hospital Patient Analyzer v2</strong><br>
    Generated on {generated_at}<br><br>
    <strong>IMPORTANT DISCLAIMER:</strong> This report is generated by an automated statistical analysis tool
    and is intended for informational and educational purposes only. It does <em>not</em> constitute
    medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional
    for any medical concerns. Statistical anomalies do not imply disease.
  </footer>
</div>

<script>
  // Tab switching
  const tabBtns   = document.querySelectorAll('.tab-btn');
  const tabPanels = document.querySelectorAll('.tab-panel');
  tabBtns.forEach(btn => {{
    btn.addEventListener('click', () => {{
      const target = btn.dataset.tab;
      tabBtns.forEach(b => b.classList.remove('active'));
      tabPanels.forEach(p => p.classList.remove('active'));
      btn.classList.add('active');
      document.getElementById('tab-' + target).classList.add('active');
    }});
  }});
</script>
</body>
</html>"""


# ------------------------------------------------------------------------------
# Helper utilities
# ------------------------------------------------------------------------------

def _fmt(val, decimals=2):
    """Format a number, returning 'N/A' for NaN."""
    if val is None or (isinstance(val, float) and math.isnan(val)):
        return "N/A"
    if isinstance(val, int):
        return f"{val:,}"
    return f"{val:,.{decimals}f}"


def _pct(part, total):
    if total == 0:
        return 0.0
    return part / total * 100


def _coverage_color(pct):
    if pct >= 80:
        return "#3fb950"
    if pct >= 50:
        return "#e3b341"
    return "#f85149"


def _tab_button(key, label, active=False):
    cls = "tab-btn active" if active else "tab-btn"
    return f'    <button class="{cls}" data-tab="{key}" id="btn-{key}">{label}</button>'


def _tab_panel(key, content, active=False):
    cls = "tab-panel active" if active else "tab-panel"
    return f'  <section class="{cls}" id="tab-{key}" role="tabpanel">\n{content}\n  </section>'


# ------------------------------------------------------------------------------
# Dataset Mode Report
# ------------------------------------------------------------------------------

def generate_dataset_report(
    output_path: str,
    patients: list,
    unique_patients: set,
    statistics: dict,
    missing_data: dict,
    duplicates: int,
    invalid_values: list,
    anomalies: list,
    correlations: dict,
    data: dict,
    sepsis_labels: np.ndarray | None = None,
    chart_sample_size: int = 30_000,
):
    """Generate the full-dataset HTML report."""
    total_rows = len(patients)
    total_missing = sum(missing_data.values())
    now = datetime.now().strftime("%B %d, %Y at %H:%M")

    # -- Sample indices for charts
    rng = np.random.default_rng(42)
    sample_idx = rng.choice(total_rows, size=min(chart_sample_size, total_rows), replace=False)
    sampled_data = {f: arr[sample_idx] for f, arr in data.items()}

    # -- Anomaly counts per feature
    anomaly_counts = {}
    for a in anomalies:
        f = a["feature"]
        anomaly_counts[f] = anomaly_counts.get(f, 0) + 1

    # -- Build charts
    histograms    = {}
    for feature, arr in sampled_data.items():
        ref  = REFERENCE_RANGES.get(feature)
        stat = statistics.get(feature, {})
        histograms[feature] = fig_to_html(build_histogram(feature, arr, stat, ref))

    corr_heatmap  = fig_to_html(build_correlation_heatmap(correlations))
    missing_chart = fig_to_html(build_missing_data_chart(missing_data, total_rows))
    anomaly_chart = fig_to_html(build_anomaly_bar_chart(anomaly_counts))
    sepsis_chart  = fig_to_html(build_sepsis_comparison(data, sepsis_labels)) if sepsis_labels is not None else None
    gender_chart  = fig_to_html(build_gender_breakdown(sampled_data, [patients[i] for i in sample_idx], list(data.keys())))

    # -- Panels --------------------------------------------------------------

    # 1. Overview Panel
    coverage_pct = 100 - _pct(total_missing, total_rows * len(statistics))
    overview_html = f"""
    <div class="stat-grid">
      <div class="stat-card"><div class="icon">&#128203;</div><div class="value">{total_rows:,}</div><div class="label">Total Observations</div></div>
      <div class="stat-card"><div class="icon">&#128100;</div><div class="value">{len(unique_patients):,}</div><div class="label">Unique Patients</div></div>
      <div class="stat-card"><div class="icon">&#9889;</div><div class="value">{duplicates:,}</div><div class="label">Duplicate Rows</div></div>
      <div class="stat-card"><div class="icon">&#128202;</div><div class="value">{len(anomalies):,}</div><div class="label">Statistical Anomalies</div></div>
      <div class="stat-card"><div class="icon">&#9989;</div><div class="value">{coverage_pct:.1f}%</div><div class="label">Data Coverage</div></div>
    </div>

    <div class="plain-box">
      <h3>&#128218; What Does This Report Show?</h3>
      <p>
        This report analyses a clinical dataset from <strong>{len(unique_patients):,} hospital patients</strong>
        across <strong>{total_rows:,} hourly observations</strong>. It examines vital signs such as heart rate,
        blood pressure, oxygen levels, and glucose to identify patterns, data gaps, and statistically
        unusual values. It does <strong>not</strong> diagnose any patient.
      </p>
    </div>

    <div class="alert alert-info">
      &#8505;&#65039; Charts in this report are generated from a random sample of
      <strong>{min(chart_sample_size, total_rows):,} rows</strong> for performance.
      All statistics (mean, std, etc.) are computed on the full dataset.
    </div>"""

    # 2. Technical Panel — for clinicians/doctors
    stat_rows = ""
    for feature, stats in statistics.items():
        ref  = REFERENCE_RANGES.get(feature, {})
        name = ref.get("name", feature)
        unit = ref.get("unit", "")
        cnt  = stats["count"]
        cov  = _pct(cnt, total_rows)
        miss = missing_data.get(feature, 0)
        anom = anomaly_counts.get(feature, 0)
        anom_pct = _pct(anom, cnt) if cnt > 0 else 0
        color = _coverage_color(cov)
        stat_rows += f"""
        <tr>
          <td><strong>{name}</strong><br><span style='color:var(--text-dim);font-size:11px;'>{feature} &bull; {unit}</span></td>
          <td class="num">{cnt:,}</td>
          <td>
            <div class="progress-wrap">
              <span style="color:{color};font-weight:600;">{cov:.1f}%</span>
              <div class="progress-bar"><div class="progress-fill" style="width:{cov:.1f}%;background:{color};"></div></div>
            </div>
          </td>
          <td class="num">{_fmt(stats.get('mean'))}</td>
          <td class="num">{_fmt(stats.get('median'))}</td>
          <td class="num">{_fmt(stats.get('std'))}</td>
          <td class="num">{_fmt(stats.get('minimum'))}</td>
          <td class="num">{_fmt(stats.get('maximum'))}</td>
          <td class="num">{miss:,} ({_pct(miss,total_rows):.1f}%)</td>
          <td class="num" style="color:{'var(--red)' if anom_pct>5 else 'var(--amber)' if anom_pct>1 else 'var(--green)'}">{anom:,} ({anom_pct:.1f}%)</td>
        </tr>"""

    corr_rows = ""
    for pair, val in correlations.items():
        if math.isnan(val):
            strength, color = "N/A", "var(--text-dim)"
        else:
            abs_val = abs(val)
            if abs_val >= 0.7:   strength, color = "Strong",   "var(--red)"
            elif abs_val >= 0.4: strength, color = "Moderate", "var(--amber)"
            elif abs_val >= 0.2: strength, color = "Weak",     "var(--blue)"
            else:                strength, color = "Negligible","var(--text-dim)"
        corr_rows += f"""
        <tr>
          <td>{pair}</td>
          <td class="num">{_fmt(val, 3)}</td>
          <td style="color:{color};font-weight:500;">{strength}</td>
        </tr>"""

    technical_html = f"""
    <div class="section-title"><span class="icon">&#128203;</span> Feature Statistics (Full Dataset)</div>
    <div class="table-wrap">
      <table class="data-table">
        <thead><tr>
          <th>Feature</th><th>Count</th><th>Coverage</th>
          <th>Mean</th><th>Median</th><th>Std Dev</th>
          <th>Min</th><th>Max</th><th>Missing</th><th>Anomalies</th>
        </tr></thead>
        <tbody>{stat_rows}</tbody>
      </table>
    </div>

    <div class="section-title" style="margin-top:32px;"><span class="icon">&#128202;</span> Correlation Analysis</div>
    <div class="chart-grid">
      <div class="chart-wrap">{corr_heatmap}</div>
    </div>
    <div class="table-wrap">
      <table class="data-table">
        <thead><tr><th>Pair</th><th>Pearson r</th><th>Strength</th></tr></thead>
        <tbody>{corr_rows}</tbody>
      </table>
    </div>

    <div class="section-title" style="margin-top:32px;"><span class="icon">&#9888;&#65039;</span> Anomaly Summary</div>
    <div class="chart-wrap">{anomaly_chart}</div>
    <div class="alert alert-warn">
      &#9888;&#65039; A statistical anomaly means a value is more than 2 standard deviations from the dataset mean.
      This is a statistical flag, not a clinical diagnosis. Many anomalies are expected in large datasets.
    </div>

    <div class="section-title" style="margin-top:32px;"><span class="icon">&#128200;</span> Data Completeness</div>
    <div class="chart-wrap">{missing_chart}</div>"""

    # 3. Plain English Panel — for guardians/patients
    plain_vitals = ""
    for feature in statistics:
        ref   = REFERENCE_RANGES.get(feature)
        if not ref:
            continue
        stats = statistics[feature]
        name  = ref["name"]
        unit  = ref["unit"]
        desc  = ref["description"]
        min_n = ref["min_normal"]
        max_n = ref["max_normal"]
        mean_val = stats.get("mean", float("nan"))
        mean_str = _fmt(mean_val)

        # Is the dataset average normal?
        if not math.isnan(mean_val) and min_n <= mean_val <= max_n:
            avg_note = f"The average value in this dataset ({mean_str} {unit}) is within the normal range ({min_n}&#8211;{max_n} {unit})."
            avg_color = "var(--green)"
        elif math.isnan(mean_val):
            avg_note = "Average not available due to missing data."
            avg_color = "var(--text-dim)"
        else:
            avg_note = f"The average value in this dataset ({mean_str} {unit}) is outside the typical normal range ({min_n}&#8211;{max_n} {unit}). This may reflect the hospital patient population studied."
            avg_color = "var(--amber)"

        plain_vitals += f"""
        <details class="collapsible">
          <summary><span>&#10024;</span> {name} &mdash; <span style="color:var(--text-dim);font-size:12px;">click to learn more</span></summary>
          <div class="collapsible-body">
            <div class="plain-box">
              <h3>What is {name}?</h3>
              <p>{desc}</p>
            </div>
            <div class="plain-box" style="border-left-color:{avg_color};">
              <h3>Dataset Average</h3>
              <p>{avg_note}</p>
              <p style="margin-top:8px;">Normal range: <strong>{min_n} &#8211; {max_n} {unit}</strong></p>
            </div>
            <div class="chart-wrap">{histograms.get(feature, '')}</div>
          </div>
        </details>"""

    plain_html = f"""
    <div class="alert alert-info">
      &#128218; This section explains the medical measurements in plain language.
      It is designed for patients, families, and non-medical readers.
    </div>

    <div class="plain-box">
      <h3>&#128105;&#8205;&#127979; Who Are These Patients?</h3>
      <p>
        This dataset comes from <strong>{len(unique_patients):,} real hospital patients</strong> admitted to an ICU
        (Intensive Care Unit). Their vital signs were recorded every hour. The average patient age is
        approximately <strong>{_fmt(statistics.get('Age', {}).get('mean', float('nan')), 0)} years</strong>.
        This dataset is used for research into sepsis — a life-threatening response to infection.
      </p>
    </div>

    <div class="section-title"><span class="icon">&#10067;</span> Understanding Each Measurement</div>
    {plain_vitals}"""

    # 4. Charts Panel
    hist_html = ""
    for feature, chart_div in histograms.items():
        ref  = REFERENCE_RANGES.get(feature, {})
        name = ref.get("name", feature)
        hist_html += f'<div class="chart-wrap"><p style="font-size:12px;color:var(--text-dim);margin-bottom:8px;">{name}</p>{chart_div}</div>'

    charts_html = f"""
    <div class="section-title"><span class="icon">&#128200;</span> Vital Sign Distributions</div>
    <div class="chart-grid">{hist_html}</div>

    <div class="section-title"><span class="icon">&#128101;</span> Gender Comparison</div>
    <div class="chart-wrap">{gender_chart}</div>"""

    if sepsis_chart:
        charts_html += f"""
    <div class="section-title"><span class="icon">&#128308;</span> Sepsis vs Non-Sepsis Comparison</div>
    <div class="chart-wrap">{sepsis_chart}</div>
    <div class="alert alert-warn">
      &#9888;&#65039; The Sepsis group shows patients flagged with SepsisLabel=1 in the dataset.
      Differences in vital signs between groups are statistical observations only.
    </div>"""

    # -- Assemble tabs
    banner_html = f"""<header class="banner">
  <span class="banner-icon">&#127973;&#65039;</span>
  <h1>Hospital Patient Data Analyzer</h1>
  <p class="subtitle">Statistical Analysis Report &bull; {len(unique_patients):,} Patients &bull; {total_rows:,} Observations</p>
  <span class="badge badge-dataset">Dataset Analysis Mode</span>
</header>"""

    tab_buttons = "\n".join([
        _tab_button("overview",  "&#127968; Overview",              active=True),
        _tab_button("technical", "&#128203; Technical (Clinicians)", active=False),
        _tab_button("plain",     "&#128218; Plain English (Guardians)", active=False),
        _tab_button("charts",    "&#128200; Charts",                active=False),
    ])
    tab_panels = "\n".join([
        _tab_panel("overview",  overview_html,  active=True),
        _tab_panel("technical", technical_html, active=False),
        _tab_panel("plain",     plain_html,     active=False),
        _tab_panel("charts",    charts_html,    active=False),
    ])

    html = HTML_TEMPLATE.format(
        page_title   = "Hospital Patient Analysis Report",
        banner_html  = banner_html,
        tab_buttons  = tab_buttons,
        tab_panels   = tab_panels,
        generated_at = now,
    )

    import os
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"  HTML report saved: {output_path}")


# ------------------------------------------------------------------------------
# Patient Assessment Mode Report
# ------------------------------------------------------------------------------

def generate_patient_report(
    output_path: str,
    patient: dict,
    assessments: list,
    statistics: dict,
    data: dict,
    chart_sample_size: int = 30_000,
):
    """Generate the personalised patient assessment HTML report."""
    now        = datetime.now().strftime("%B %d, %Y at %H:%M")
    name       = patient.get("name", "Unknown")
    age        = patient.get("age", "N/A")
    gender     = patient.get("gender", "N/A")
    gender_str = {"M": "Male", "F": "Female"}.get(gender, gender)

    # Sample data for chart overlays
    total_rows = max(len(v) for v in data.values()) if data else 0
    rng = np.random.default_rng(42)
    sample_idx = rng.choice(total_rows, size=min(chart_sample_size, total_rows), replace=False)
    sampled_data = {f: arr[sample_idx] for f, arr in data.items()}

    # -- Status summary card
    n_normal   = sum(1 for a in assessments if a["status_info"]["status"] == "normal")
    n_low      = sum(1 for a in assessments if "low" in a["status_info"]["status"])
    n_high     = sum(1 for a in assessments if "high" in a["status_info"]["status"])
    n_skipped  = sum(1 for a in assessments if a["status_info"]["status"] == "skipped")
    n_critical = sum(1 for a in assessments if "critical" in a["status_info"]["status"])

    # -- Vital cards
    vital_cards_html = ""
    for a in assessments:
        feature  = a["feature"]
        value    = a["value"]
        ref      = a["ref"]
        si       = a["status_info"]
        name_f   = ref.get("name", feature)
        unit     = ref.get("unit", "")
        min_n    = ref.get("min_normal", "")
        max_n    = ref.get("max_normal", "")
        desc     = ref.get("description", "")
        color    = si["color"]
        emoji    = si["emoji"]
        label    = si["label"]
        message  = si["message"]

        if value is None:
            val_display = "&mdash;"
            unit_display = ""
        else:
            val_display  = f"{value:.1f}"
            unit_display = unit

        vital_cards_html += f"""
        <div class="vital-card" style="--status-color:{color};">
          <div class="vc-head">
            <div class="vc-name">{emoji} {name_f}</div>
            <div class="vc-status">{label}</div>
          </div>
          <div class="vc-value">{val_display}</div>
          <div class="vc-unit">{unit_display}</div>
          <div class="vc-range">Normal range: {min_n}&ndash;{max_n} {unit}</div>
          <div class="vc-desc">{desc}</div>
          <div class="vc-msg">{message}</div>
        </div>"""

    # -- Charts with patient value overlays
    chart_html = ""
    for a in assessments:
        feature = a["feature"]
        value   = a["value"]
        ref     = REFERENCE_RANGES.get(feature)
        stats   = statistics.get(feature, {})
        arr     = sampled_data.get(feature)
        if arr is None or ref is None:
            continue
        fig = build_histogram(feature, arr, stats, ref, patient_value=value)
        chart_html += f'<div class="chart-wrap">{fig_to_html(fig)}</div>'

    # -- Overview panel
    overview_html = f"""
    <div class="stat-grid">
      <div class="stat-card"><div class="icon">&#9989;</div><div class="value" style="color:var(--green)">{n_normal}</div><div class="label">Normal Vitals</div></div>
      <div class="stat-card"><div class="icon">&#128308;</div><div class="value" style="color:var(--red)">{n_critical}</div><div class="label">Critically Out of Range</div></div>
      <div class="stat-card"><div class="icon">&#128993;</div><div class="value" style="color:var(--amber)">{n_low + n_high - n_critical}</div><div class="label">Borderline Values</div></div>
      <div class="stat-card"><div class="icon">&#8709;</div><div class="value" style="color:var(--text-dim)">{n_skipped}</div><div class="label">Not Provided</div></div>
    </div>

    <div class="plain-box">
      <h3>&#128100; Patient: {name}</h3>
      <p>Age: <strong>{age}</strong> years &bull; Gender: <strong>{gender_str}</strong> &bull; Assessed: <strong>{now}</strong></p>
    </div>

    {f'<div class="alert alert-danger">&#9888;&#65039; <strong>Attention:</strong> One or more measurements are critically outside the normal range. Please consult a healthcare professional immediately.</div>' if n_critical > 0 else ''}
    {f'<div class="alert alert-warn">&#9888;&#65039; <strong>Note:</strong> Some measurements are outside the normal range. Please discuss these results with a healthcare professional.</div>' if (n_low + n_high - n_critical) > 0 else ''}
    {f'<div class="alert alert-info">&#9989; <strong>All provided measurements are within normal ranges.</strong> Continue to follow your healthcare provider guidance.</div>' if n_normal == len(assessments) - n_skipped and n_low + n_high == 0 else ''}"""

    # -- Vital signs panel
    vitals_html = f"""
    <div class="alert alert-info">
      &#128218; Each card shows a traffic-light status. Normal values are shown in green,
      borderline in amber, and out-of-range values in red. Each card also explains
      what the measurement means in plain language.
    </div>
    <div class="vital-grid">{vital_cards_html}</div>"""

    # -- Charts panel
    charts_section_html = f"""
    <div class="alert alert-info">
      &#128200; Each chart shows the distribution of that vital sign across the hospital patient dataset.
      The <strong>vertical colored line</strong> marks the patient's own value.
      The <strong>green shaded area</strong> shows the clinical normal range.
    </div>
    <div class="chart-grid">{chart_html}</div>"""

    # -- Banner
    banner_html = f"""<header class="banner">
  <span class="banner-icon">&#128100;</span>
  <h1>Patient Vital Sign Assessment</h1>
  <p class="subtitle">{name} &bull; Age {age} &bull; {gender_str}</p>
  <span class="badge badge-patient">Patient Assessment Mode</span>
</header>"""

    tab_buttons = "\n".join([
        _tab_button("overview", "&#127968; Summary",        active=True),
        _tab_button("vitals",   "&#10084;&#65039; Vital Signs", active=False),
        _tab_button("charts",   "&#128200; Population Charts",  active=False),
    ])
    tab_panels = "\n".join([
        _tab_panel("overview", overview_html,       active=True),
        _tab_panel("vitals",   vitals_html,         active=False),
        _tab_panel("charts",   charts_section_html, active=False),
    ])

    html = HTML_TEMPLATE.format(
        page_title   = f"Patient Report: {name}",
        banner_html  = banner_html,
        tab_buttons  = tab_buttons,
        tab_panels   = tab_panels,
        generated_at = now,
    )

    import os
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"  Patient HTML report saved: {output_path}")
